version: '3'
services:
  outvio-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - REDIS_HOST=outvio-redis
    ports:
      - 3000:3000
    volumes:
      - .:/app/
    restart: always
    depends_on:
      - outvio-redis
    networks:
      outvio:
        aliases:
          - 'outvio-api'
networks:
  outvio:
