version: '3'
services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    environment:
      SERVICE_NAME: 'redis'
    networks:
      nestjs:
        aliases:
          - 'redis'
networks:
  nestjs:
