version: '3'
services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - REDIS_HOST=redis
    ports:
      - 3000:3000
    volumes:
      - .:/app/
    restart: always
    depends_on:
      - redis
    networks:
      nestjs:
        aliases:
          - 'nestjs-api'
networks:
  nestjs:
