version: '3'
services:
  outvio-redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    environment:
      SERVICE_NAME: 'outvio-redis'
    networks:
      outvio:
        aliases:
          - 'outvio-redis'
networks:
  outvio:
